### ISSUE TITLE
餐厅详情页面修改餐厅详情页面修改

### ISSUE THREAD

**Issue by leasonlive** [zxhy-xjl/sz-wechat#14]
1、调整布局
2、增加本月扫桌次数
3、营业执照
4、食品经营许可证
5、健康证
6、食品安全等级
7、行政处罚
8、投诉举报
9、如果消费记录中有投诉，显示投诉状态
详细请看钉钉中的范例图

**Comment by Fachion** [comment]
这个投诉状态是显示本用户消费的历史投诉，还是所有用户的历史投诉？
